### PR TITLE
Changed Unacceptable Behavior for deadline section

### PR DESCRIPTION
**Pull request by Lancasterwu**

### CODE REVIEW

**Review by shafferz — CHANGES_REQUESTED** [review]
I think these look good, though I'm not convinced that the point:

> * Discuss things with team members after due dates.

Will get accepted. By "things," do you mean issues? Do you mean the due dates themselves? I think more specificity is going to be required.

**Review by aubreypc — CHANGES_REQUESTED** [review]
See my comment here https://github.com/Allegheny-Computer-Science-203-S2019/cs203-S2019-conduct/pull/13/files/fac8bf21ce42b676d4077ccfd166f7782189e5e1#r253277868

**Review by Michionlion — CHANGES_REQUESTED** [review]
I'm not sure of the point of discussing things after due dates -- shouldn't it be before due dates?

I'm also not sure of `Communicate reasons for work being late after the deadline.` -- Should students not attempt to justify the reason their work was late?

I also agree with @shafferz and @aubreypc above.

**Review by Michionlion — APPROVED** [review]

**Review by aubreypc — APPROVED** [review]
Looks good now! 👍

**Review by shafferz — APPROVED** [review]
Looks better. Thanks for your work!

**Pull request merged**
